# Generated by Django 5.2.14 on 2026-06-12 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FuelStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('truckstop_id', models.IntegerField(help_text='Original OPIS Truckstop ID')),
                ('name', models.CharField(help_text='Name of the truck stop', max_length=255)),
                ('address', models.CharField(help_text='Physical address', max_length=255)),
                ('city', models.CharField(help_text='City', max_length=100)),
                ('state', models.CharField(help_text='State abbreviation', max_length=50)),
                ('retail_price', models.DecimalField(decimal_places=4, help_text='Retail price per gallon', max_digits=10)),
                ('latitude', models.FloatField(help_text='Latitude coordinate')),
                ('longitude', models.FloatField(help_text='Longitude coordinate')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Fuel Station',
                'verbose_name_plural': 'Fuel Stations',
                'indexes': [models.Index(fields=['city'], name='fs_city_idx'), models.Index(fields=['state'], name='fs_state_idx'), models.Index(fields=['retail_price'], name='fs_price_idx'), models.Index(fields=['latitude'], name='fs_lat_idx'), models.Index(fields=['longitude'], name='fs_lon_idx')],
            },
        ),
    ]
